#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_Web.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QL_BANHANG")]
	public partial class dbQL_BanHangDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTable_BANSANPHAM(Table_BANSANPHAM instance);
    partial void UpdateTable_BANSANPHAM(Table_BANSANPHAM instance);
    partial void DeleteTable_BANSANPHAM(Table_BANSANPHAM instance);
    partial void InsertTable_TUYCHON(Table_TUYCHON instance);
    partial void UpdateTable_TUYCHON(Table_TUYCHON instance);
    partial void DeleteTable_TUYCHON(Table_TUYCHON instance);
    partial void InsertTable_DONHANG(Table_DONHANG instance);
    partial void UpdateTable_DONHANG(Table_DONHANG instance);
    partial void DeleteTable_DONHANG(Table_DONHANG instance);
    partial void InsertTable_DONHANG_DM(Table_DONHANG_DM instance);
    partial void UpdateTable_DONHANG_DM(Table_DONHANG_DM instance);
    partial void DeleteTable_DONHANG_DM(Table_DONHANG_DM instance);
    partial void InsertTable_KHACHHANG(Table_KHACHHANG instance);
    partial void UpdateTable_KHACHHANG(Table_KHACHHANG instance);
    partial void DeleteTable_KHACHHANG(Table_KHACHHANG instance);
    partial void InsertTable_LOAINHANVIEN(Table_LOAINHANVIEN instance);
    partial void UpdateTable_LOAINHANVIEN(Table_LOAINHANVIEN instance);
    partial void DeleteTable_LOAINHANVIEN(Table_LOAINHANVIEN instance);
    partial void InsertTable_LOAISANPHAM(Table_LOAISANPHAM instance);
    partial void UpdateTable_LOAISANPHAM(Table_LOAISANPHAM instance);
    partial void DeleteTable_LOAISANPHAM(Table_LOAISANPHAM instance);
    partial void InsertTable_MUCHINHANH(Table_MUCHINHANH instance);
    partial void UpdateTable_MUCHINHANH(Table_MUCHINHANH instance);
    partial void DeleteTable_MUCHINHANH(Table_MUCHINHANH instance);
    partial void InsertTable_NHANVIEN(Table_NHANVIEN instance);
    partial void UpdateTable_NHANVIEN(Table_NHANVIEN instance);
    partial void DeleteTable_NHANVIEN(Table_NHANVIEN instance);
    partial void InsertTable_NHAPKHO(Table_NHAPKHO instance);
    partial void UpdateTable_NHAPKHO(Table_NHAPKHO instance);
    partial void DeleteTable_NHAPKHO(Table_NHAPKHO instance);
    partial void InsertTable_NhaSX(Table_NhaSX instance);
    partial void UpdateTable_NhaSX(Table_NhaSX instance);
    partial void DeleteTable_NhaSX(Table_NhaSX instance);
    partial void InsertTable_SANPHAM(Table_SANPHAM instance);
    partial void UpdateTable_SANPHAM(Table_SANPHAM instance);
    partial void DeleteTable_SANPHAM(Table_SANPHAM instance);
    #endregion
		
		public dbQL_BanHangDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QL_BANHANGConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbQL_BanHangDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQL_BanHangDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQL_BanHangDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQL_BanHangDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Table_BANSANPHAM> Table_BANSANPHAMs
		{
			get
			{
				return this.GetTable<Table_BANSANPHAM>();
			}
		}
		
		public System.Data.Linq.Table<Table_TUYCHON> Table_TUYCHONs
		{
			get
			{
				return this.GetTable<Table_TUYCHON>();
			}
		}
		
		public System.Data.Linq.Table<Table_DONHANG> Table_DONHANGs
		{
			get
			{
				return this.GetTable<Table_DONHANG>();
			}
		}
		
		public System.Data.Linq.Table<Table_DONHANG_DM> Table_DONHANG_DMs
		{
			get
			{
				return this.GetTable<Table_DONHANG_DM>();
			}
		}
		
		public System.Data.Linq.Table<Table_KHACHHANG> Table_KHACHHANGs
		{
			get
			{
				return this.GetTable<Table_KHACHHANG>();
			}
		}
		
		public System.Data.Linq.Table<Table_LOAINHANVIEN> Table_LOAINHANVIENs
		{
			get
			{
				return this.GetTable<Table_LOAINHANVIEN>();
			}
		}
		
		public System.Data.Linq.Table<Table_LOAISANPHAM> Table_LOAISANPHAMs
		{
			get
			{
				return this.GetTable<Table_LOAISANPHAM>();
			}
		}
		
		public System.Data.Linq.Table<Table_MUCHINHANH> Table_MUCHINHANHs
		{
			get
			{
				return this.GetTable<Table_MUCHINHANH>();
			}
		}
		
		public System.Data.Linq.Table<Table_NHANVIEN> Table_NHANVIENs
		{
			get
			{
				return this.GetTable<Table_NHANVIEN>();
			}
		}
		
		public System.Data.Linq.Table<Table_NHAPKHO> Table_NHAPKHOs
		{
			get
			{
				return this.GetTable<Table_NHAPKHO>();
			}
		}
		
		public System.Data.Linq.Table<Table_NhaSX> Table_NhaSXes
		{
			get
			{
				return this.GetTable<Table_NhaSX>();
			}
		}
		
		public System.Data.Linq.Table<Table_SANPHAM> Table_SANPHAMs
		{
			get
			{
				return this.GetTable<Table_SANPHAM>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_BANSANPHAM")]
	public partial class Table_BANSANPHAM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_BANSANPHAM;
		
		private int _ID_DONHANG;
		
		private System.Nullable<double> _ThanhToanTienCK;
		
		private System.Nullable<double> _TinhTrangThanhToan;
		
		private EntityRef<Table_DONHANG> _Table_DONHANG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_BANSANPHAMChanging(int value);
    partial void OnID_BANSANPHAMChanged();
    partial void OnID_DONHANGChanging(int value);
    partial void OnID_DONHANGChanged();
    partial void OnThanhToanTienCKChanging(System.Nullable<double> value);
    partial void OnThanhToanTienCKChanged();
    partial void OnTinhTrangThanhToanChanging(System.Nullable<double> value);
    partial void OnTinhTrangThanhToanChanged();
    #endregion
		
		public Table_BANSANPHAM()
		{
			this._Table_DONHANG = default(EntityRef<Table_DONHANG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_BANSANPHAM", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_BANSANPHAM
		{
			get
			{
				return this._ID_BANSANPHAM;
			}
			set
			{
				if ((this._ID_BANSANPHAM != value))
				{
					this.OnID_BANSANPHAMChanging(value);
					this.SendPropertyChanging();
					this._ID_BANSANPHAM = value;
					this.SendPropertyChanged("ID_BANSANPHAM");
					this.OnID_BANSANPHAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DONHANG", DbType="Int NOT NULL")]
		public int ID_DONHANG
		{
			get
			{
				return this._ID_DONHANG;
			}
			set
			{
				if ((this._ID_DONHANG != value))
				{
					if (this._Table_DONHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_DONHANGChanging(value);
					this.SendPropertyChanging();
					this._ID_DONHANG = value;
					this.SendPropertyChanged("ID_DONHANG");
					this.OnID_DONHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhToanTienCK", DbType="Float")]
		public System.Nullable<double> ThanhToanTienCK
		{
			get
			{
				return this._ThanhToanTienCK;
			}
			set
			{
				if ((this._ThanhToanTienCK != value))
				{
					this.OnThanhToanTienCKChanging(value);
					this.SendPropertyChanging();
					this._ThanhToanTienCK = value;
					this.SendPropertyChanged("ThanhToanTienCK");
					this.OnThanhToanTienCKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrangThanhToan", DbType="Float")]
		public System.Nullable<double> TinhTrangThanhToan
		{
			get
			{
				return this._TinhTrangThanhToan;
			}
			set
			{
				if ((this._TinhTrangThanhToan != value))
				{
					this.OnTinhTrangThanhToanChanging(value);
					this.SendPropertyChanging();
					this._TinhTrangThanhToan = value;
					this.SendPropertyChanged("TinhTrangThanhToan");
					this.OnTinhTrangThanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_DONHANG_Table_BANSANPHAM", Storage="_Table_DONHANG", ThisKey="ID_DONHANG", OtherKey="ID_DONHANG", IsForeignKey=true)]
		public Table_DONHANG Table_DONHANG
		{
			get
			{
				return this._Table_DONHANG.Entity;
			}
			set
			{
				Table_DONHANG previousValue = this._Table_DONHANG.Entity;
				if (((previousValue != value) 
							|| (this._Table_DONHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Table_DONHANG.Entity = null;
						previousValue.Table_BANSANPHAMs.Remove(this);
					}
					this._Table_DONHANG.Entity = value;
					if ((value != null))
					{
						value.Table_BANSANPHAMs.Add(this);
						this._ID_DONHANG = value.ID_DONHANG;
					}
					else
					{
						this._ID_DONHANG = default(int);
					}
					this.SendPropertyChanged("Table_DONHANG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_TUYCHON")]
	public partial class Table_TUYCHON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_TUYCHON;
		
		private int _ID_SANPHAM;
		
		private string _TuyChon;
		
		private System.Nullable<double> _DonGia;
		
		private System.Nullable<int> _SoLuong;
		
		private EntityRef<Table_SANPHAM> _Table_SANPHAM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_TUYCHONChanging(int value);
    partial void OnID_TUYCHONChanged();
    partial void OnID_SANPHAMChanging(int value);
    partial void OnID_SANPHAMChanged();
    partial void OnTuyChonChanging(string value);
    partial void OnTuyChonChanged();
    partial void OnDonGiaChanging(System.Nullable<double> value);
    partial void OnDonGiaChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    #endregion
		
		public Table_TUYCHON()
		{
			this._Table_SANPHAM = default(EntityRef<Table_SANPHAM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TUYCHON", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_TUYCHON
		{
			get
			{
				return this._ID_TUYCHON;
			}
			set
			{
				if ((this._ID_TUYCHON != value))
				{
					this.OnID_TUYCHONChanging(value);
					this.SendPropertyChanging();
					this._ID_TUYCHON = value;
					this.SendPropertyChanged("ID_TUYCHON");
					this.OnID_TUYCHONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_SANPHAM", DbType="Int NOT NULL")]
		public int ID_SANPHAM
		{
			get
			{
				return this._ID_SANPHAM;
			}
			set
			{
				if ((this._ID_SANPHAM != value))
				{
					if (this._Table_SANPHAM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_SANPHAMChanging(value);
					this.SendPropertyChanging();
					this._ID_SANPHAM = value;
					this.SendPropertyChanged("ID_SANPHAM");
					this.OnID_SANPHAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TuyChon", DbType="NVarChar(50)")]
		public string TuyChon
		{
			get
			{
				return this._TuyChon;
			}
			set
			{
				if ((this._TuyChon != value))
				{
					this.OnTuyChonChanging(value);
					this.SendPropertyChanging();
					this._TuyChon = value;
					this.SendPropertyChanged("TuyChon");
					this.OnTuyChonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Float")]
		public System.Nullable<double> DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this.OnDonGiaChanging(value);
					this.SendPropertyChanging();
					this._DonGia = value;
					this.SendPropertyChanged("DonGia");
					this.OnDonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_SANPHAM_Table_TUYCHON", Storage="_Table_SANPHAM", ThisKey="ID_SANPHAM", OtherKey="ID_SANPHAM", IsForeignKey=true)]
		public Table_SANPHAM Table_SANPHAM
		{
			get
			{
				return this._Table_SANPHAM.Entity;
			}
			set
			{
				Table_SANPHAM previousValue = this._Table_SANPHAM.Entity;
				if (((previousValue != value) 
							|| (this._Table_SANPHAM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Table_SANPHAM.Entity = null;
						previousValue.Table_TUYCHONs.Remove(this);
					}
					this._Table_SANPHAM.Entity = value;
					if ((value != null))
					{
						value.Table_TUYCHONs.Add(this);
						this._ID_SANPHAM = value.ID_SANPHAM;
					}
					else
					{
						this._ID_SANPHAM = default(int);
					}
					this.SendPropertyChanged("Table_SANPHAM");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_DONHANG")]
	public partial class Table_DONHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_DONHANG;
		
		private System.Nullable<int> _ID_NGUOIBAN;
		
		private System.Nullable<int> _ID_NGUOIGIAO;
		
		private System.Nullable<int> _ID_NGUOICHOT;
		
		private System.Nullable<int> _ID_KHACHHANG;
		
		private System.Nullable<double> _TONGTIEN;
		
		private System.Nullable<System.DateTime> _NgayGiaoDich;
		
		private System.Nullable<bool> _Damua;
		
		private System.Nullable<System.DateTime> _NgayGiaoHang;
		
		private string _GhiChu;
		
		private System.Nullable<bool> _TinhTrang;
		
		private string _PhanHoi;
		
		private EntitySet<Table_BANSANPHAM> _Table_BANSANPHAMs;
		
		private EntitySet<Table_DONHANG_DM> _Table_DONHANG_DMs;
		
		private EntityRef<Table_KHACHHANG> _Table_KHACHHANG;
		
		private EntityRef<Table_NHANVIEN> _Table_NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_DONHANGChanging(int value);
    partial void OnID_DONHANGChanged();
    partial void OnID_NGUOIBANChanging(System.Nullable<int> value);
    partial void OnID_NGUOIBANChanged();
    partial void OnID_NGUOIGIAOChanging(System.Nullable<int> value);
    partial void OnID_NGUOIGIAOChanged();
    partial void OnID_NGUOICHOTChanging(System.Nullable<int> value);
    partial void OnID_NGUOICHOTChanged();
    partial void OnID_KHACHHANGChanging(System.Nullable<int> value);
    partial void OnID_KHACHHANGChanged();
    partial void OnTONGTIENChanging(System.Nullable<double> value);
    partial void OnTONGTIENChanged();
    partial void OnNgayGiaoDichChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayGiaoDichChanged();
    partial void OnDamuaChanging(System.Nullable<bool> value);
    partial void OnDamuaChanged();
    partial void OnNgayGiaoHangChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayGiaoHangChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnTinhTrangChanging(System.Nullable<bool> value);
    partial void OnTinhTrangChanged();
    partial void OnPhanHoiChanging(string value);
    partial void OnPhanHoiChanged();
    #endregion
		
		public Table_DONHANG()
		{
			this._Table_BANSANPHAMs = new EntitySet<Table_BANSANPHAM>(new Action<Table_BANSANPHAM>(this.attach_Table_BANSANPHAMs), new Action<Table_BANSANPHAM>(this.detach_Table_BANSANPHAMs));
			this._Table_DONHANG_DMs = new EntitySet<Table_DONHANG_DM>(new Action<Table_DONHANG_DM>(this.attach_Table_DONHANG_DMs), new Action<Table_DONHANG_DM>(this.detach_Table_DONHANG_DMs));
			this._Table_KHACHHANG = default(EntityRef<Table_KHACHHANG>);
			this._Table_NHANVIEN = default(EntityRef<Table_NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DONHANG", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_DONHANG
		{
			get
			{
				return this._ID_DONHANG;
			}
			set
			{
				if ((this._ID_DONHANG != value))
				{
					this.OnID_DONHANGChanging(value);
					this.SendPropertyChanging();
					this._ID_DONHANG = value;
					this.SendPropertyChanged("ID_DONHANG");
					this.OnID_DONHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_NGUOIBAN", DbType="Int")]
		public System.Nullable<int> ID_NGUOIBAN
		{
			get
			{
				return this._ID_NGUOIBAN;
			}
			set
			{
				if ((this._ID_NGUOIBAN != value))
				{
					if (this._Table_NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_NGUOIBANChanging(value);
					this.SendPropertyChanging();
					this._ID_NGUOIBAN = value;
					this.SendPropertyChanged("ID_NGUOIBAN");
					this.OnID_NGUOIBANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_NGUOIGIAO", DbType="Int")]
		public System.Nullable<int> ID_NGUOIGIAO
		{
			get
			{
				return this._ID_NGUOIGIAO;
			}
			set
			{
				if ((this._ID_NGUOIGIAO != value))
				{
					this.OnID_NGUOIGIAOChanging(value);
					this.SendPropertyChanging();
					this._ID_NGUOIGIAO = value;
					this.SendPropertyChanged("ID_NGUOIGIAO");
					this.OnID_NGUOIGIAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_NGUOICHOT", DbType="Int")]
		public System.Nullable<int> ID_NGUOICHOT
		{
			get
			{
				return this._ID_NGUOICHOT;
			}
			set
			{
				if ((this._ID_NGUOICHOT != value))
				{
					this.OnID_NGUOICHOTChanging(value);
					this.SendPropertyChanging();
					this._ID_NGUOICHOT = value;
					this.SendPropertyChanged("ID_NGUOICHOT");
					this.OnID_NGUOICHOTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_KHACHHANG", DbType="Int")]
		public System.Nullable<int> ID_KHACHHANG
		{
			get
			{
				return this._ID_KHACHHANG;
			}
			set
			{
				if ((this._ID_KHACHHANG != value))
				{
					if (this._Table_KHACHHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_KHACHHANGChanging(value);
					this.SendPropertyChanging();
					this._ID_KHACHHANG = value;
					this.SendPropertyChanged("ID_KHACHHANG");
					this.OnID_KHACHHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGTIEN", DbType="Float")]
		public System.Nullable<double> TONGTIEN
		{
			get
			{
				return this._TONGTIEN;
			}
			set
			{
				if ((this._TONGTIEN != value))
				{
					this.OnTONGTIENChanging(value);
					this.SendPropertyChanging();
					this._TONGTIEN = value;
					this.SendPropertyChanged("TONGTIEN");
					this.OnTONGTIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayGiaoDich", DbType="Date")]
		public System.Nullable<System.DateTime> NgayGiaoDich
		{
			get
			{
				return this._NgayGiaoDich;
			}
			set
			{
				if ((this._NgayGiaoDich != value))
				{
					this.OnNgayGiaoDichChanging(value);
					this.SendPropertyChanging();
					this._NgayGiaoDich = value;
					this.SendPropertyChanged("NgayGiaoDich");
					this.OnNgayGiaoDichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Damua", DbType="Bit")]
		public System.Nullable<bool> Damua
		{
			get
			{
				return this._Damua;
			}
			set
			{
				if ((this._Damua != value))
				{
					this.OnDamuaChanging(value);
					this.SendPropertyChanging();
					this._Damua = value;
					this.SendPropertyChanged("Damua");
					this.OnDamuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayGiaoHang", DbType="Date")]
		public System.Nullable<System.DateTime> NgayGiaoHang
		{
			get
			{
				return this._NgayGiaoHang;
			}
			set
			{
				if ((this._NgayGiaoHang != value))
				{
					this.OnNgayGiaoHangChanging(value);
					this.SendPropertyChanging();
					this._NgayGiaoHang = value;
					this.SendPropertyChanged("NgayGiaoHang");
					this.OnNgayGiaoHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(500)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrang", DbType="Bit")]
		public System.Nullable<bool> TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					this.OnTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TinhTrang = value;
					this.SendPropertyChanged("TinhTrang");
					this.OnTinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhanHoi", DbType="NVarChar(500)")]
		public string PhanHoi
		{
			get
			{
				return this._PhanHoi;
			}
			set
			{
				if ((this._PhanHoi != value))
				{
					this.OnPhanHoiChanging(value);
					this.SendPropertyChanging();
					this._PhanHoi = value;
					this.SendPropertyChanged("PhanHoi");
					this.OnPhanHoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_DONHANG_Table_BANSANPHAM", Storage="_Table_BANSANPHAMs", ThisKey="ID_DONHANG", OtherKey="ID_DONHANG")]
		public EntitySet<Table_BANSANPHAM> Table_BANSANPHAMs
		{
			get
			{
				return this._Table_BANSANPHAMs;
			}
			set
			{
				this._Table_BANSANPHAMs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_DONHANG_Table_DONHANG_DM", Storage="_Table_DONHANG_DMs", ThisKey="ID_DONHANG", OtherKey="ID_DONHANG")]
		public EntitySet<Table_DONHANG_DM> Table_DONHANG_DMs
		{
			get
			{
				return this._Table_DONHANG_DMs;
			}
			set
			{
				this._Table_DONHANG_DMs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_KHACHHANG_Table_DONHANG", Storage="_Table_KHACHHANG", ThisKey="ID_KHACHHANG", OtherKey="ID_KHACHHANG", IsForeignKey=true)]
		public Table_KHACHHANG Table_KHACHHANG
		{
			get
			{
				return this._Table_KHACHHANG.Entity;
			}
			set
			{
				Table_KHACHHANG previousValue = this._Table_KHACHHANG.Entity;
				if (((previousValue != value) 
							|| (this._Table_KHACHHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Table_KHACHHANG.Entity = null;
						previousValue.Table_DONHANGs.Remove(this);
					}
					this._Table_KHACHHANG.Entity = value;
					if ((value != null))
					{
						value.Table_DONHANGs.Add(this);
						this._ID_KHACHHANG = value.ID_KHACHHANG;
					}
					else
					{
						this._ID_KHACHHANG = default(Nullable<int>);
					}
					this.SendPropertyChanged("Table_KHACHHANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_NHANVIEN_Table_DONHANG", Storage="_Table_NHANVIEN", ThisKey="ID_NGUOIBAN", OtherKey="ID_NHANVIEN", IsForeignKey=true)]
		public Table_NHANVIEN Table_NHANVIEN
		{
			get
			{
				return this._Table_NHANVIEN.Entity;
			}
			set
			{
				Table_NHANVIEN previousValue = this._Table_NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._Table_NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Table_NHANVIEN.Entity = null;
						previousValue.Table_DONHANGs.Remove(this);
					}
					this._Table_NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.Table_DONHANGs.Add(this);
						this._ID_NGUOIBAN = value.ID_NHANVIEN;
					}
					else
					{
						this._ID_NGUOIBAN = default(Nullable<int>);
					}
					this.SendPropertyChanged("Table_NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Table_BANSANPHAMs(Table_BANSANPHAM entity)
		{
			this.SendPropertyChanging();
			entity.Table_DONHANG = this;
		}
		
		private void detach_Table_BANSANPHAMs(Table_BANSANPHAM entity)
		{
			this.SendPropertyChanging();
			entity.Table_DONHANG = null;
		}
		
		private void attach_Table_DONHANG_DMs(Table_DONHANG_DM entity)
		{
			this.SendPropertyChanging();
			entity.Table_DONHANG = this;
		}
		
		private void detach_Table_DONHANG_DMs(Table_DONHANG_DM entity)
		{
			this.SendPropertyChanging();
			entity.Table_DONHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_DONHANG_DM")]
	public partial class Table_DONHANG_DM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_DONHANG_DM;
		
		private int _ID_DONHANG;
		
		private int _ID_SANPHAM;
		
		private string _TuyChon;
		
		private System.Nullable<int> _SoLuong;
		
		private System.Nullable<double> _Giatien;
		
		private System.Nullable<bool> _TinhTrang;
		
		private string _GHICHU;
		
		private EntityRef<Table_DONHANG> _Table_DONHANG;
		
		private EntityRef<Table_SANPHAM> _Table_SANPHAM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_DONHANG_DMChanging(int value);
    partial void OnID_DONHANG_DMChanged();
    partial void OnID_DONHANGChanging(int value);
    partial void OnID_DONHANGChanged();
    partial void OnID_SANPHAMChanging(int value);
    partial void OnID_SANPHAMChanged();
    partial void OnTuyChonChanging(string value);
    partial void OnTuyChonChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnGiatienChanging(System.Nullable<double> value);
    partial void OnGiatienChanged();
    partial void OnTinhTrangChanging(System.Nullable<bool> value);
    partial void OnTinhTrangChanged();
    partial void OnGHICHUChanging(string value);
    partial void OnGHICHUChanged();
    #endregion
		
		public Table_DONHANG_DM()
		{
			this._Table_DONHANG = default(EntityRef<Table_DONHANG>);
			this._Table_SANPHAM = default(EntityRef<Table_SANPHAM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DONHANG_DM", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_DONHANG_DM
		{
			get
			{
				return this._ID_DONHANG_DM;
			}
			set
			{
				if ((this._ID_DONHANG_DM != value))
				{
					this.OnID_DONHANG_DMChanging(value);
					this.SendPropertyChanging();
					this._ID_DONHANG_DM = value;
					this.SendPropertyChanged("ID_DONHANG_DM");
					this.OnID_DONHANG_DMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DONHANG", DbType="Int NOT NULL")]
		public int ID_DONHANG
		{
			get
			{
				return this._ID_DONHANG;
			}
			set
			{
				if ((this._ID_DONHANG != value))
				{
					if (this._Table_DONHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_DONHANGChanging(value);
					this.SendPropertyChanging();
					this._ID_DONHANG = value;
					this.SendPropertyChanged("ID_DONHANG");
					this.OnID_DONHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_SANPHAM", DbType="Int NOT NULL")]
		public int ID_SANPHAM
		{
			get
			{
				return this._ID_SANPHAM;
			}
			set
			{
				if ((this._ID_SANPHAM != value))
				{
					if (this._Table_SANPHAM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_SANPHAMChanging(value);
					this.SendPropertyChanging();
					this._ID_SANPHAM = value;
					this.SendPropertyChanged("ID_SANPHAM");
					this.OnID_SANPHAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TuyChon", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TuyChon
		{
			get
			{
				return this._TuyChon;
			}
			set
			{
				if ((this._TuyChon != value))
				{
					this.OnTuyChonChanging(value);
					this.SendPropertyChanging();
					this._TuyChon = value;
					this.SendPropertyChanged("TuyChon");
					this.OnTuyChonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Giatien", DbType="Float")]
		public System.Nullable<double> Giatien
		{
			get
			{
				return this._Giatien;
			}
			set
			{
				if ((this._Giatien != value))
				{
					this.OnGiatienChanging(value);
					this.SendPropertyChanging();
					this._Giatien = value;
					this.SendPropertyChanged("Giatien");
					this.OnGiatienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrang", DbType="Bit")]
		public System.Nullable<bool> TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					this.OnTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TinhTrang = value;
					this.SendPropertyChanged("TinhTrang");
					this.OnTinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GHICHU", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string GHICHU
		{
			get
			{
				return this._GHICHU;
			}
			set
			{
				if ((this._GHICHU != value))
				{
					this.OnGHICHUChanging(value);
					this.SendPropertyChanging();
					this._GHICHU = value;
					this.SendPropertyChanged("GHICHU");
					this.OnGHICHUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_DONHANG_Table_DONHANG_DM", Storage="_Table_DONHANG", ThisKey="ID_DONHANG", OtherKey="ID_DONHANG", IsForeignKey=true)]
		public Table_DONHANG Table_DONHANG
		{
			get
			{
				return this._Table_DONHANG.Entity;
			}
			set
			{
				Table_DONHANG previousValue = this._Table_DONHANG.Entity;
				if (((previousValue != value) 
							|| (this._Table_DONHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Table_DONHANG.Entity = null;
						previousValue.Table_DONHANG_DMs.Remove(this);
					}
					this._Table_DONHANG.Entity = value;
					if ((value != null))
					{
						value.Table_DONHANG_DMs.Add(this);
						this._ID_DONHANG = value.ID_DONHANG;
					}
					else
					{
						this._ID_DONHANG = default(int);
					}
					this.SendPropertyChanged("Table_DONHANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_SANPHAM_Table_DONHANG_DM", Storage="_Table_SANPHAM", ThisKey="ID_SANPHAM", OtherKey="ID_SANPHAM", IsForeignKey=true)]
		public Table_SANPHAM Table_SANPHAM
		{
			get
			{
				return this._Table_SANPHAM.Entity;
			}
			set
			{
				Table_SANPHAM previousValue = this._Table_SANPHAM.Entity;
				if (((previousValue != value) 
							|| (this._Table_SANPHAM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Table_SANPHAM.Entity = null;
						previousValue.Table_DONHANG_DMs.Remove(this);
					}
					this._Table_SANPHAM.Entity = value;
					if ((value != null))
					{
						value.Table_DONHANG_DMs.Add(this);
						this._ID_SANPHAM = value.ID_SANPHAM;
					}
					else
					{
						this._ID_SANPHAM = default(int);
					}
					this.SendPropertyChanged("Table_SANPHAM");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_KHACHHANG")]
	public partial class Table_KHACHHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_KHACHHANG;
		
		private string _HoTen;
		
		private string _SDT;
		
		private string _DiaChi;
		
		private string _Email;
		
		private string _Facebook;
		
		private string _Skype;
		
		private string _Whatapp;
		
		private string _Telegram;
		
		private System.Nullable<int> _ID_GIOITHIEU;
		
		private System.Nullable<System.DateTime> _NgayGioiThieu;
		
		private EntitySet<Table_DONHANG> _Table_DONHANGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_KHACHHANGChanging(int value);
    partial void OnID_KHACHHANGChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnFacebookChanging(string value);
    partial void OnFacebookChanged();
    partial void OnSkypeChanging(string value);
    partial void OnSkypeChanged();
    partial void OnWhatappChanging(string value);
    partial void OnWhatappChanged();
    partial void OnTelegramChanging(string value);
    partial void OnTelegramChanged();
    partial void OnID_GIOITHIEUChanging(System.Nullable<int> value);
    partial void OnID_GIOITHIEUChanged();
    partial void OnNgayGioiThieuChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayGioiThieuChanged();
    #endregion
		
		public Table_KHACHHANG()
		{
			this._Table_DONHANGs = new EntitySet<Table_DONHANG>(new Action<Table_DONHANG>(this.attach_Table_DONHANGs), new Action<Table_DONHANG>(this.detach_Table_DONHANGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_KHACHHANG", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_KHACHHANG
		{
			get
			{
				return this._ID_KHACHHANG;
			}
			set
			{
				if ((this._ID_KHACHHANG != value))
				{
					this.OnID_KHACHHANGChanging(value);
					this.SendPropertyChanging();
					this._ID_KHACHHANG = value;
					this.SendPropertyChanged("ID_KHACHHANG");
					this.OnID_KHACHHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(10)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(100)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Facebook", DbType="VarChar(100)")]
		public string Facebook
		{
			get
			{
				return this._Facebook;
			}
			set
			{
				if ((this._Facebook != value))
				{
					this.OnFacebookChanging(value);
					this.SendPropertyChanging();
					this._Facebook = value;
					this.SendPropertyChanged("Facebook");
					this.OnFacebookChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Skype", DbType="VarChar(100)")]
		public string Skype
		{
			get
			{
				return this._Skype;
			}
			set
			{
				if ((this._Skype != value))
				{
					this.OnSkypeChanging(value);
					this.SendPropertyChanging();
					this._Skype = value;
					this.SendPropertyChanged("Skype");
					this.OnSkypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Whatapp", DbType="VarChar(100)")]
		public string Whatapp
		{
			get
			{
				return this._Whatapp;
			}
			set
			{
				if ((this._Whatapp != value))
				{
					this.OnWhatappChanging(value);
					this.SendPropertyChanging();
					this._Whatapp = value;
					this.SendPropertyChanged("Whatapp");
					this.OnWhatappChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telegram", DbType="VarChar(100)")]
		public string Telegram
		{
			get
			{
				return this._Telegram;
			}
			set
			{
				if ((this._Telegram != value))
				{
					this.OnTelegramChanging(value);
					this.SendPropertyChanging();
					this._Telegram = value;
					this.SendPropertyChanged("Telegram");
					this.OnTelegramChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_GIOITHIEU", DbType="Int")]
		public System.Nullable<int> ID_GIOITHIEU
		{
			get
			{
				return this._ID_GIOITHIEU;
			}
			set
			{
				if ((this._ID_GIOITHIEU != value))
				{
					this.OnID_GIOITHIEUChanging(value);
					this.SendPropertyChanging();
					this._ID_GIOITHIEU = value;
					this.SendPropertyChanged("ID_GIOITHIEU");
					this.OnID_GIOITHIEUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayGioiThieu", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayGioiThieu
		{
			get
			{
				return this._NgayGioiThieu;
			}
			set
			{
				if ((this._NgayGioiThieu != value))
				{
					this.OnNgayGioiThieuChanging(value);
					this.SendPropertyChanging();
					this._NgayGioiThieu = value;
					this.SendPropertyChanged("NgayGioiThieu");
					this.OnNgayGioiThieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_KHACHHANG_Table_DONHANG", Storage="_Table_DONHANGs", ThisKey="ID_KHACHHANG", OtherKey="ID_KHACHHANG")]
		public EntitySet<Table_DONHANG> Table_DONHANGs
		{
			get
			{
				return this._Table_DONHANGs;
			}
			set
			{
				this._Table_DONHANGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Table_DONHANGs(Table_DONHANG entity)
		{
			this.SendPropertyChanging();
			entity.Table_KHACHHANG = this;
		}
		
		private void detach_Table_DONHANGs(Table_DONHANG entity)
		{
			this.SendPropertyChanging();
			entity.Table_KHACHHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_LOAINHANVIEN")]
	public partial class Table_LOAINHANVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_LOAINHANVIEN;
		
		private string _Tenloainhanvien;
		
		private EntitySet<Table_NHANVIEN> _Table_NHANVIENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_LOAINHANVIENChanging(int value);
    partial void OnID_LOAINHANVIENChanged();
    partial void OnTenloainhanvienChanging(string value);
    partial void OnTenloainhanvienChanged();
    #endregion
		
		public Table_LOAINHANVIEN()
		{
			this._Table_NHANVIENs = new EntitySet<Table_NHANVIEN>(new Action<Table_NHANVIEN>(this.attach_Table_NHANVIENs), new Action<Table_NHANVIEN>(this.detach_Table_NHANVIENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_LOAINHANVIEN", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_LOAINHANVIEN
		{
			get
			{
				return this._ID_LOAINHANVIEN;
			}
			set
			{
				if ((this._ID_LOAINHANVIEN != value))
				{
					this.OnID_LOAINHANVIENChanging(value);
					this.SendPropertyChanging();
					this._ID_LOAINHANVIEN = value;
					this.SendPropertyChanged("ID_LOAINHANVIEN");
					this.OnID_LOAINHANVIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenloainhanvien", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string Tenloainhanvien
		{
			get
			{
				return this._Tenloainhanvien;
			}
			set
			{
				if ((this._Tenloainhanvien != value))
				{
					this.OnTenloainhanvienChanging(value);
					this.SendPropertyChanging();
					this._Tenloainhanvien = value;
					this.SendPropertyChanged("Tenloainhanvien");
					this.OnTenloainhanvienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_LOAINHANVIEN_Table_NHANVIEN", Storage="_Table_NHANVIENs", ThisKey="ID_LOAINHANVIEN", OtherKey="ID_LOAINHANVIEN")]
		public EntitySet<Table_NHANVIEN> Table_NHANVIENs
		{
			get
			{
				return this._Table_NHANVIENs;
			}
			set
			{
				this._Table_NHANVIENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Table_NHANVIENs(Table_NHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.Table_LOAINHANVIEN = this;
		}
		
		private void detach_Table_NHANVIENs(Table_NHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.Table_LOAINHANVIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_LOAISANPHAM")]
	public partial class Table_LOAISANPHAM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_LOAISANPHAM;
		
		private string _TenLoaiSanPham;
		
		private int _Root;
		
		private string _TenThuMuc;
		
		private EntitySet<Table_SANPHAM> _Table_SANPHAMs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_LOAISANPHAMChanging(int value);
    partial void OnID_LOAISANPHAMChanged();
    partial void OnTenLoaiSanPhamChanging(string value);
    partial void OnTenLoaiSanPhamChanged();
    partial void OnRootChanging(int value);
    partial void OnRootChanged();
    partial void OnTenThuMucChanging(string value);
    partial void OnTenThuMucChanged();
    #endregion
		
		public Table_LOAISANPHAM()
		{
			this._Table_SANPHAMs = new EntitySet<Table_SANPHAM>(new Action<Table_SANPHAM>(this.attach_Table_SANPHAMs), new Action<Table_SANPHAM>(this.detach_Table_SANPHAMs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_LOAISANPHAM", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_LOAISANPHAM
		{
			get
			{
				return this._ID_LOAISANPHAM;
			}
			set
			{
				if ((this._ID_LOAISANPHAM != value))
				{
					this.OnID_LOAISANPHAMChanging(value);
					this.SendPropertyChanging();
					this._ID_LOAISANPHAM = value;
					this.SendPropertyChanged("ID_LOAISANPHAM");
					this.OnID_LOAISANPHAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoaiSanPham", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string TenLoaiSanPham
		{
			get
			{
				return this._TenLoaiSanPham;
			}
			set
			{
				if ((this._TenLoaiSanPham != value))
				{
					this.OnTenLoaiSanPhamChanging(value);
					this.SendPropertyChanging();
					this._TenLoaiSanPham = value;
					this.SendPropertyChanged("TenLoaiSanPham");
					this.OnTenLoaiSanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Root", DbType="Int NOT NULL")]
		public int Root
		{
			get
			{
				return this._Root;
			}
			set
			{
				if ((this._Root != value))
				{
					this.OnRootChanging(value);
					this.SendPropertyChanging();
					this._Root = value;
					this.SendPropertyChanged("Root");
					this.OnRootChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenThuMuc", DbType="VarChar(100)")]
		public string TenThuMuc
		{
			get
			{
				return this._TenThuMuc;
			}
			set
			{
				if ((this._TenThuMuc != value))
				{
					this.OnTenThuMucChanging(value);
					this.SendPropertyChanging();
					this._TenThuMuc = value;
					this.SendPropertyChanged("TenThuMuc");
					this.OnTenThuMucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_LOAISANPHAM_Table_SANPHAM", Storage="_Table_SANPHAMs", ThisKey="ID_LOAISANPHAM", OtherKey="ID_LOAISANPHAM")]
		public EntitySet<Table_SANPHAM> Table_SANPHAMs
		{
			get
			{
				return this._Table_SANPHAMs;
			}
			set
			{
				this._Table_SANPHAMs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Table_SANPHAMs(Table_SANPHAM entity)
		{
			this.SendPropertyChanging();
			entity.Table_LOAISANPHAM = this;
		}
		
		private void detach_Table_SANPHAMs(Table_SANPHAM entity)
		{
			this.SendPropertyChanging();
			entity.Table_LOAISANPHAM = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_MUCHINHANH")]
	public partial class Table_MUCHINHANH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_HINHANH;
		
		private int _ID_SANPHAM;
		
		private string _HINHANH_N;
		
		private EntityRef<Table_SANPHAM> _Table_SANPHAM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_HINHANHChanging(int value);
    partial void OnID_HINHANHChanged();
    partial void OnID_SANPHAMChanging(int value);
    partial void OnID_SANPHAMChanged();
    partial void OnHINHANH_NChanging(string value);
    partial void OnHINHANH_NChanged();
    #endregion
		
		public Table_MUCHINHANH()
		{
			this._Table_SANPHAM = default(EntityRef<Table_SANPHAM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_HINHANH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_HINHANH
		{
			get
			{
				return this._ID_HINHANH;
			}
			set
			{
				if ((this._ID_HINHANH != value))
				{
					this.OnID_HINHANHChanging(value);
					this.SendPropertyChanging();
					this._ID_HINHANH = value;
					this.SendPropertyChanged("ID_HINHANH");
					this.OnID_HINHANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_SANPHAM", DbType="Int NOT NULL")]
		public int ID_SANPHAM
		{
			get
			{
				return this._ID_SANPHAM;
			}
			set
			{
				if ((this._ID_SANPHAM != value))
				{
					if (this._Table_SANPHAM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_SANPHAMChanging(value);
					this.SendPropertyChanging();
					this._ID_SANPHAM = value;
					this.SendPropertyChanged("ID_SANPHAM");
					this.OnID_SANPHAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINHANH_N", DbType="VarChar(200)")]
		public string HINHANH_N
		{
			get
			{
				return this._HINHANH_N;
			}
			set
			{
				if ((this._HINHANH_N != value))
				{
					this.OnHINHANH_NChanging(value);
					this.SendPropertyChanging();
					this._HINHANH_N = value;
					this.SendPropertyChanged("HINHANH_N");
					this.OnHINHANH_NChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_SANPHAM_Table_MUCHINHANH", Storage="_Table_SANPHAM", ThisKey="ID_SANPHAM", OtherKey="ID_SANPHAM", IsForeignKey=true)]
		public Table_SANPHAM Table_SANPHAM
		{
			get
			{
				return this._Table_SANPHAM.Entity;
			}
			set
			{
				Table_SANPHAM previousValue = this._Table_SANPHAM.Entity;
				if (((previousValue != value) 
							|| (this._Table_SANPHAM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Table_SANPHAM.Entity = null;
						previousValue.Table_MUCHINHANHs.Remove(this);
					}
					this._Table_SANPHAM.Entity = value;
					if ((value != null))
					{
						value.Table_MUCHINHANHs.Add(this);
						this._ID_SANPHAM = value.ID_SANPHAM;
					}
					else
					{
						this._ID_SANPHAM = default(int);
					}
					this.SendPropertyChanged("Table_SANPHAM");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_NHANVIEN")]
	public partial class Table_NHANVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_NHANVIEN;
		
		private string _HoTen;
		
		private string _Username;
		
		private string _Password;
		
		private System.Nullable<bool> _GioiTinh;
		
		private string _SDT;
		
		private string _TKBank;
		
		private string _Diachi;
		
		private string _Email;
		
		private string _Skype;
		
		private string _ANHDAIDIEN;
		
		private System.Nullable<int> _ID_LOAINHANVIEN;
		
		private string _Code;
		
		private string _ActiveCode;
		
		private EntitySet<Table_DONHANG> _Table_DONHANGs;
		
		private EntitySet<Table_NHAPKHO> _Table_NHAPKHOs;
		
		private EntityRef<Table_LOAINHANVIEN> _Table_LOAINHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_NHANVIENChanging(int value);
    partial void OnID_NHANVIENChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnGioiTinhChanging(System.Nullable<bool> value);
    partial void OnGioiTinhChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnTKBankChanging(string value);
    partial void OnTKBankChanged();
    partial void OnDiachiChanging(string value);
    partial void OnDiachiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnSkypeChanging(string value);
    partial void OnSkypeChanged();
    partial void OnANHDAIDIENChanging(string value);
    partial void OnANHDAIDIENChanged();
    partial void OnID_LOAINHANVIENChanging(System.Nullable<int> value);
    partial void OnID_LOAINHANVIENChanged();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnActiveCodeChanging(string value);
    partial void OnActiveCodeChanged();
    #endregion
		
		public Table_NHANVIEN()
		{
			this._Table_DONHANGs = new EntitySet<Table_DONHANG>(new Action<Table_DONHANG>(this.attach_Table_DONHANGs), new Action<Table_DONHANG>(this.detach_Table_DONHANGs));
			this._Table_NHAPKHOs = new EntitySet<Table_NHAPKHO>(new Action<Table_NHAPKHO>(this.attach_Table_NHAPKHOs), new Action<Table_NHAPKHO>(this.detach_Table_NHAPKHOs));
			this._Table_LOAINHANVIEN = default(EntityRef<Table_LOAINHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_NHANVIEN", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_NHANVIEN
		{
			get
			{
				return this._ID_NHANVIEN;
			}
			set
			{
				if ((this._ID_NHANVIEN != value))
				{
					this.OnID_NHANVIENChanging(value);
					this.SendPropertyChanging();
					this._ID_NHANVIEN = value;
					this.SendPropertyChanged("ID_NHANVIEN");
					this.OnID_NHANVIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(100)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(100)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="Bit")]
		public System.Nullable<bool> GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(10)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TKBank", DbType="VarChar(100)")]
		public string TKBank
		{
			get
			{
				return this._TKBank;
			}
			set
			{
				if ((this._TKBank != value))
				{
					this.OnTKBankChanging(value);
					this.SendPropertyChanging();
					this._TKBank = value;
					this.SendPropertyChanged("TKBank");
					this.OnTKBankChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diachi", DbType="NVarChar(500)")]
		public string Diachi
		{
			get
			{
				return this._Diachi;
			}
			set
			{
				if ((this._Diachi != value))
				{
					this.OnDiachiChanging(value);
					this.SendPropertyChanging();
					this._Diachi = value;
					this.SendPropertyChanged("Diachi");
					this.OnDiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Skype", DbType="VarChar(100)")]
		public string Skype
		{
			get
			{
				return this._Skype;
			}
			set
			{
				if ((this._Skype != value))
				{
					this.OnSkypeChanging(value);
					this.SendPropertyChanging();
					this._Skype = value;
					this.SendPropertyChanged("Skype");
					this.OnSkypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANHDAIDIEN", DbType="VarChar(100)")]
		public string ANHDAIDIEN
		{
			get
			{
				return this._ANHDAIDIEN;
			}
			set
			{
				if ((this._ANHDAIDIEN != value))
				{
					this.OnANHDAIDIENChanging(value);
					this.SendPropertyChanging();
					this._ANHDAIDIEN = value;
					this.SendPropertyChanged("ANHDAIDIEN");
					this.OnANHDAIDIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_LOAINHANVIEN", DbType="Int")]
		public System.Nullable<int> ID_LOAINHANVIEN
		{
			get
			{
				return this._ID_LOAINHANVIEN;
			}
			set
			{
				if ((this._ID_LOAINHANVIEN != value))
				{
					if (this._Table_LOAINHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_LOAINHANVIENChanging(value);
					this.SendPropertyChanging();
					this._ID_LOAINHANVIEN = value;
					this.SendPropertyChanged("ID_LOAINHANVIEN");
					this.OnID_LOAINHANVIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(100)")]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActiveCode", DbType="NVarChar(100)")]
		public string ActiveCode
		{
			get
			{
				return this._ActiveCode;
			}
			set
			{
				if ((this._ActiveCode != value))
				{
					this.OnActiveCodeChanging(value);
					this.SendPropertyChanging();
					this._ActiveCode = value;
					this.SendPropertyChanged("ActiveCode");
					this.OnActiveCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_NHANVIEN_Table_DONHANG", Storage="_Table_DONHANGs", ThisKey="ID_NHANVIEN", OtherKey="ID_NGUOIBAN")]
		public EntitySet<Table_DONHANG> Table_DONHANGs
		{
			get
			{
				return this._Table_DONHANGs;
			}
			set
			{
				this._Table_DONHANGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_NHANVIEN_Table_NHAPKHO", Storage="_Table_NHAPKHOs", ThisKey="ID_NHANVIEN", OtherKey="ID_NHANVIEN")]
		public EntitySet<Table_NHAPKHO> Table_NHAPKHOs
		{
			get
			{
				return this._Table_NHAPKHOs;
			}
			set
			{
				this._Table_NHAPKHOs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_LOAINHANVIEN_Table_NHANVIEN", Storage="_Table_LOAINHANVIEN", ThisKey="ID_LOAINHANVIEN", OtherKey="ID_LOAINHANVIEN", IsForeignKey=true)]
		public Table_LOAINHANVIEN Table_LOAINHANVIEN
		{
			get
			{
				return this._Table_LOAINHANVIEN.Entity;
			}
			set
			{
				Table_LOAINHANVIEN previousValue = this._Table_LOAINHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._Table_LOAINHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Table_LOAINHANVIEN.Entity = null;
						previousValue.Table_NHANVIENs.Remove(this);
					}
					this._Table_LOAINHANVIEN.Entity = value;
					if ((value != null))
					{
						value.Table_NHANVIENs.Add(this);
						this._ID_LOAINHANVIEN = value.ID_LOAINHANVIEN;
					}
					else
					{
						this._ID_LOAINHANVIEN = default(Nullable<int>);
					}
					this.SendPropertyChanged("Table_LOAINHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Table_DONHANGs(Table_DONHANG entity)
		{
			this.SendPropertyChanging();
			entity.Table_NHANVIEN = this;
		}
		
		private void detach_Table_DONHANGs(Table_DONHANG entity)
		{
			this.SendPropertyChanging();
			entity.Table_NHANVIEN = null;
		}
		
		private void attach_Table_NHAPKHOs(Table_NHAPKHO entity)
		{
			this.SendPropertyChanging();
			entity.Table_NHANVIEN = this;
		}
		
		private void detach_Table_NHAPKHOs(Table_NHAPKHO entity)
		{
			this.SendPropertyChanging();
			entity.Table_NHANVIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_NHAPKHO")]
	public partial class Table_NHAPKHO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_NHAPKHO;
		
		private int _ID_SANPHAM;
		
		private int _ID_NHANVIEN;
		
		private System.Nullable<int> _SoLuong;
		
		private System.Nullable<System.DateTime> _NgayNhap;
		
		private EntityRef<Table_NHANVIEN> _Table_NHANVIEN;
		
		private EntityRef<Table_SANPHAM> _Table_SANPHAM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_NHAPKHOChanging(int value);
    partial void OnID_NHAPKHOChanged();
    partial void OnID_SANPHAMChanging(int value);
    partial void OnID_SANPHAMChanged();
    partial void OnID_NHANVIENChanging(int value);
    partial void OnID_NHANVIENChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnNgayNhapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayNhapChanged();
    #endregion
		
		public Table_NHAPKHO()
		{
			this._Table_NHANVIEN = default(EntityRef<Table_NHANVIEN>);
			this._Table_SANPHAM = default(EntityRef<Table_SANPHAM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_NHAPKHO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_NHAPKHO
		{
			get
			{
				return this._ID_NHAPKHO;
			}
			set
			{
				if ((this._ID_NHAPKHO != value))
				{
					this.OnID_NHAPKHOChanging(value);
					this.SendPropertyChanging();
					this._ID_NHAPKHO = value;
					this.SendPropertyChanged("ID_NHAPKHO");
					this.OnID_NHAPKHOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_SANPHAM", DbType="Int NOT NULL")]
		public int ID_SANPHAM
		{
			get
			{
				return this._ID_SANPHAM;
			}
			set
			{
				if ((this._ID_SANPHAM != value))
				{
					if (this._Table_SANPHAM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_SANPHAMChanging(value);
					this.SendPropertyChanging();
					this._ID_SANPHAM = value;
					this.SendPropertyChanged("ID_SANPHAM");
					this.OnID_SANPHAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_NHANVIEN", DbType="Int NOT NULL")]
		public int ID_NHANVIEN
		{
			get
			{
				return this._ID_NHANVIEN;
			}
			set
			{
				if ((this._ID_NHANVIEN != value))
				{
					if (this._Table_NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_NHANVIENChanging(value);
					this.SendPropertyChanging();
					this._ID_NHANVIEN = value;
					this.SendPropertyChanged("ID_NHANVIEN");
					this.OnID_NHANVIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayNhap", DbType="Date")]
		public System.Nullable<System.DateTime> NgayNhap
		{
			get
			{
				return this._NgayNhap;
			}
			set
			{
				if ((this._NgayNhap != value))
				{
					this.OnNgayNhapChanging(value);
					this.SendPropertyChanging();
					this._NgayNhap = value;
					this.SendPropertyChanged("NgayNhap");
					this.OnNgayNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_NHANVIEN_Table_NHAPKHO", Storage="_Table_NHANVIEN", ThisKey="ID_NHANVIEN", OtherKey="ID_NHANVIEN", IsForeignKey=true)]
		public Table_NHANVIEN Table_NHANVIEN
		{
			get
			{
				return this._Table_NHANVIEN.Entity;
			}
			set
			{
				Table_NHANVIEN previousValue = this._Table_NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._Table_NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Table_NHANVIEN.Entity = null;
						previousValue.Table_NHAPKHOs.Remove(this);
					}
					this._Table_NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.Table_NHAPKHOs.Add(this);
						this._ID_NHANVIEN = value.ID_NHANVIEN;
					}
					else
					{
						this._ID_NHANVIEN = default(int);
					}
					this.SendPropertyChanged("Table_NHANVIEN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_SANPHAM_Table_NHAPKHO", Storage="_Table_SANPHAM", ThisKey="ID_SANPHAM", OtherKey="ID_SANPHAM", IsForeignKey=true)]
		public Table_SANPHAM Table_SANPHAM
		{
			get
			{
				return this._Table_SANPHAM.Entity;
			}
			set
			{
				Table_SANPHAM previousValue = this._Table_SANPHAM.Entity;
				if (((previousValue != value) 
							|| (this._Table_SANPHAM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Table_SANPHAM.Entity = null;
						previousValue.Table_NHAPKHOs.Remove(this);
					}
					this._Table_SANPHAM.Entity = value;
					if ((value != null))
					{
						value.Table_NHAPKHOs.Add(this);
						this._ID_SANPHAM = value.ID_SANPHAM;
					}
					else
					{
						this._ID_SANPHAM = default(int);
					}
					this.SendPropertyChanged("Table_SANPHAM");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_NhaSX")]
	public partial class Table_NhaSX : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_NSX;
		
		private string _NhaSX;
		
		private string _NoiSX;
		
		private EntitySet<Table_SANPHAM> _Table_SANPHAMs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_NSXChanging(int value);
    partial void OnID_NSXChanged();
    partial void OnNhaSXChanging(string value);
    partial void OnNhaSXChanged();
    partial void OnNoiSXChanging(string value);
    partial void OnNoiSXChanged();
    #endregion
		
		public Table_NhaSX()
		{
			this._Table_SANPHAMs = new EntitySet<Table_SANPHAM>(new Action<Table_SANPHAM>(this.attach_Table_SANPHAMs), new Action<Table_SANPHAM>(this.detach_Table_SANPHAMs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_NSX", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_NSX
		{
			get
			{
				return this._ID_NSX;
			}
			set
			{
				if ((this._ID_NSX != value))
				{
					this.OnID_NSXChanging(value);
					this.SendPropertyChanging();
					this._ID_NSX = value;
					this.SendPropertyChanged("ID_NSX");
					this.OnID_NSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhaSX", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NhaSX
		{
			get
			{
				return this._NhaSX;
			}
			set
			{
				if ((this._NhaSX != value))
				{
					this.OnNhaSXChanging(value);
					this.SendPropertyChanging();
					this._NhaSX = value;
					this.SendPropertyChanged("NhaSX");
					this.OnNhaSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiSX", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string NoiSX
		{
			get
			{
				return this._NoiSX;
			}
			set
			{
				if ((this._NoiSX != value))
				{
					this.OnNoiSXChanging(value);
					this.SendPropertyChanging();
					this._NoiSX = value;
					this.SendPropertyChanged("NoiSX");
					this.OnNoiSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_NhaSX_Table_SANPHAM", Storage="_Table_SANPHAMs", ThisKey="ID_NSX", OtherKey="ID_NSX")]
		public EntitySet<Table_SANPHAM> Table_SANPHAMs
		{
			get
			{
				return this._Table_SANPHAMs;
			}
			set
			{
				this._Table_SANPHAMs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Table_SANPHAMs(Table_SANPHAM entity)
		{
			this.SendPropertyChanging();
			entity.Table_NhaSX = this;
		}
		
		private void detach_Table_SANPHAMs(Table_SANPHAM entity)
		{
			this.SendPropertyChanging();
			entity.Table_NhaSX = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_SANPHAM")]
	public partial class Table_SANPHAM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_SANPHAM;
		
		private int _ID_LOAISANPHAM;
		
		private string _TenSanPham;
		
		private string _ChiTiet;
		
		private string _MAUSAC;
		
		private string _SIZE;
		
		private string _CHATLIEU;
		
		private double _DonGia;
		
		private System.Nullable<double> _ChietKhau;
		
		private System.Nullable<int> _ID_NSX;
		
		private System.Nullable<bool> _Ngung;
		
		private System.Nullable<int> _SoLuong;
		
		private string _HINHANH;
		
		private System.Nullable<int> _VIEWER;
		
		private System.Nullable<bool> _UuTien;
		
		private EntitySet<Table_TUYCHON> _Table_TUYCHONs;
		
		private EntitySet<Table_DONHANG_DM> _Table_DONHANG_DMs;
		
		private EntitySet<Table_MUCHINHANH> _Table_MUCHINHANHs;
		
		private EntitySet<Table_NHAPKHO> _Table_NHAPKHOs;
		
		private EntityRef<Table_LOAISANPHAM> _Table_LOAISANPHAM;
		
		private EntityRef<Table_NhaSX> _Table_NhaSX;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_SANPHAMChanging(int value);
    partial void OnID_SANPHAMChanged();
    partial void OnID_LOAISANPHAMChanging(int value);
    partial void OnID_LOAISANPHAMChanged();
    partial void OnTenSanPhamChanging(string value);
    partial void OnTenSanPhamChanged();
    partial void OnChiTietChanging(string value);
    partial void OnChiTietChanged();
    partial void OnMAUSACChanging(string value);
    partial void OnMAUSACChanged();
    partial void OnSIZEChanging(string value);
    partial void OnSIZEChanged();
    partial void OnCHATLIEUChanging(string value);
    partial void OnCHATLIEUChanged();
    partial void OnDonGiaChanging(double value);
    partial void OnDonGiaChanged();
    partial void OnChietKhauChanging(System.Nullable<double> value);
    partial void OnChietKhauChanged();
    partial void OnID_NSXChanging(System.Nullable<int> value);
    partial void OnID_NSXChanged();
    partial void OnNgungChanging(System.Nullable<bool> value);
    partial void OnNgungChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnHINHANHChanging(string value);
    partial void OnHINHANHChanged();
    partial void OnVIEWERChanging(System.Nullable<int> value);
    partial void OnVIEWERChanged();
    partial void OnUuTienChanging(System.Nullable<bool> value);
    partial void OnUuTienChanged();
    #endregion
		
		public Table_SANPHAM()
		{
			this._Table_TUYCHONs = new EntitySet<Table_TUYCHON>(new Action<Table_TUYCHON>(this.attach_Table_TUYCHONs), new Action<Table_TUYCHON>(this.detach_Table_TUYCHONs));
			this._Table_DONHANG_DMs = new EntitySet<Table_DONHANG_DM>(new Action<Table_DONHANG_DM>(this.attach_Table_DONHANG_DMs), new Action<Table_DONHANG_DM>(this.detach_Table_DONHANG_DMs));
			this._Table_MUCHINHANHs = new EntitySet<Table_MUCHINHANH>(new Action<Table_MUCHINHANH>(this.attach_Table_MUCHINHANHs), new Action<Table_MUCHINHANH>(this.detach_Table_MUCHINHANHs));
			this._Table_NHAPKHOs = new EntitySet<Table_NHAPKHO>(new Action<Table_NHAPKHO>(this.attach_Table_NHAPKHOs), new Action<Table_NHAPKHO>(this.detach_Table_NHAPKHOs));
			this._Table_LOAISANPHAM = default(EntityRef<Table_LOAISANPHAM>);
			this._Table_NhaSX = default(EntityRef<Table_NhaSX>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_SANPHAM", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_SANPHAM
		{
			get
			{
				return this._ID_SANPHAM;
			}
			set
			{
				if ((this._ID_SANPHAM != value))
				{
					this.OnID_SANPHAMChanging(value);
					this.SendPropertyChanging();
					this._ID_SANPHAM = value;
					this.SendPropertyChanged("ID_SANPHAM");
					this.OnID_SANPHAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_LOAISANPHAM", DbType="Int NOT NULL")]
		public int ID_LOAISANPHAM
		{
			get
			{
				return this._ID_LOAISANPHAM;
			}
			set
			{
				if ((this._ID_LOAISANPHAM != value))
				{
					if (this._Table_LOAISANPHAM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_LOAISANPHAMChanging(value);
					this.SendPropertyChanging();
					this._ID_LOAISANPHAM = value;
					this.SendPropertyChanged("ID_LOAISANPHAM");
					this.OnID_LOAISANPHAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSanPham", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string TenSanPham
		{
			get
			{
				return this._TenSanPham;
			}
			set
			{
				if ((this._TenSanPham != value))
				{
					this.OnTenSanPhamChanging(value);
					this.SendPropertyChanging();
					this._TenSanPham = value;
					this.SendPropertyChanged("TenSanPham");
					this.OnTenSanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChiTiet", DbType="NVarChar(500)")]
		public string ChiTiet
		{
			get
			{
				return this._ChiTiet;
			}
			set
			{
				if ((this._ChiTiet != value))
				{
					this.OnChiTietChanging(value);
					this.SendPropertyChanging();
					this._ChiTiet = value;
					this.SendPropertyChanged("ChiTiet");
					this.OnChiTietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAUSAC", DbType="NVarChar(100)")]
		public string MAUSAC
		{
			get
			{
				return this._MAUSAC;
			}
			set
			{
				if ((this._MAUSAC != value))
				{
					this.OnMAUSACChanging(value);
					this.SendPropertyChanging();
					this._MAUSAC = value;
					this.SendPropertyChanged("MAUSAC");
					this.OnMAUSACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SIZE", DbType="NVarChar(100)")]
		public string SIZE
		{
			get
			{
				return this._SIZE;
			}
			set
			{
				if ((this._SIZE != value))
				{
					this.OnSIZEChanging(value);
					this.SendPropertyChanging();
					this._SIZE = value;
					this.SendPropertyChanged("SIZE");
					this.OnSIZEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHATLIEU", DbType="NVarChar(100)")]
		public string CHATLIEU
		{
			get
			{
				return this._CHATLIEU;
			}
			set
			{
				if ((this._CHATLIEU != value))
				{
					this.OnCHATLIEUChanging(value);
					this.SendPropertyChanging();
					this._CHATLIEU = value;
					this.SendPropertyChanged("CHATLIEU");
					this.OnCHATLIEUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Float NOT NULL")]
		public double DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this.OnDonGiaChanging(value);
					this.SendPropertyChanging();
					this._DonGia = value;
					this.SendPropertyChanged("DonGia");
					this.OnDonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChietKhau", DbType="Float")]
		public System.Nullable<double> ChietKhau
		{
			get
			{
				return this._ChietKhau;
			}
			set
			{
				if ((this._ChietKhau != value))
				{
					this.OnChietKhauChanging(value);
					this.SendPropertyChanging();
					this._ChietKhau = value;
					this.SendPropertyChanged("ChietKhau");
					this.OnChietKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_NSX", DbType="Int")]
		public System.Nullable<int> ID_NSX
		{
			get
			{
				return this._ID_NSX;
			}
			set
			{
				if ((this._ID_NSX != value))
				{
					if (this._Table_NhaSX.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_NSXChanging(value);
					this.SendPropertyChanging();
					this._ID_NSX = value;
					this.SendPropertyChanged("ID_NSX");
					this.OnID_NSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngung", DbType="Bit")]
		public System.Nullable<bool> Ngung
		{
			get
			{
				return this._Ngung;
			}
			set
			{
				if ((this._Ngung != value))
				{
					this.OnNgungChanging(value);
					this.SendPropertyChanging();
					this._Ngung = value;
					this.SendPropertyChanged("Ngung");
					this.OnNgungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINHANH", DbType="VarChar(50)")]
		public string HINHANH
		{
			get
			{
				return this._HINHANH;
			}
			set
			{
				if ((this._HINHANH != value))
				{
					this.OnHINHANHChanging(value);
					this.SendPropertyChanging();
					this._HINHANH = value;
					this.SendPropertyChanged("HINHANH");
					this.OnHINHANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VIEWER", DbType="Int")]
		public System.Nullable<int> VIEWER
		{
			get
			{
				return this._VIEWER;
			}
			set
			{
				if ((this._VIEWER != value))
				{
					this.OnVIEWERChanging(value);
					this.SendPropertyChanging();
					this._VIEWER = value;
					this.SendPropertyChanged("VIEWER");
					this.OnVIEWERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UuTien", DbType="Bit")]
		public System.Nullable<bool> UuTien
		{
			get
			{
				return this._UuTien;
			}
			set
			{
				if ((this._UuTien != value))
				{
					this.OnUuTienChanging(value);
					this.SendPropertyChanging();
					this._UuTien = value;
					this.SendPropertyChanged("UuTien");
					this.OnUuTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_SANPHAM_Table_TUYCHON", Storage="_Table_TUYCHONs", ThisKey="ID_SANPHAM", OtherKey="ID_SANPHAM")]
		public EntitySet<Table_TUYCHON> Table_TUYCHONs
		{
			get
			{
				return this._Table_TUYCHONs;
			}
			set
			{
				this._Table_TUYCHONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_SANPHAM_Table_DONHANG_DM", Storage="_Table_DONHANG_DMs", ThisKey="ID_SANPHAM", OtherKey="ID_SANPHAM")]
		public EntitySet<Table_DONHANG_DM> Table_DONHANG_DMs
		{
			get
			{
				return this._Table_DONHANG_DMs;
			}
			set
			{
				this._Table_DONHANG_DMs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_SANPHAM_Table_MUCHINHANH", Storage="_Table_MUCHINHANHs", ThisKey="ID_SANPHAM", OtherKey="ID_SANPHAM")]
		public EntitySet<Table_MUCHINHANH> Table_MUCHINHANHs
		{
			get
			{
				return this._Table_MUCHINHANHs;
			}
			set
			{
				this._Table_MUCHINHANHs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_SANPHAM_Table_NHAPKHO", Storage="_Table_NHAPKHOs", ThisKey="ID_SANPHAM", OtherKey="ID_SANPHAM")]
		public EntitySet<Table_NHAPKHO> Table_NHAPKHOs
		{
			get
			{
				return this._Table_NHAPKHOs;
			}
			set
			{
				this._Table_NHAPKHOs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_LOAISANPHAM_Table_SANPHAM", Storage="_Table_LOAISANPHAM", ThisKey="ID_LOAISANPHAM", OtherKey="ID_LOAISANPHAM", IsForeignKey=true)]
		public Table_LOAISANPHAM Table_LOAISANPHAM
		{
			get
			{
				return this._Table_LOAISANPHAM.Entity;
			}
			set
			{
				Table_LOAISANPHAM previousValue = this._Table_LOAISANPHAM.Entity;
				if (((previousValue != value) 
							|| (this._Table_LOAISANPHAM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Table_LOAISANPHAM.Entity = null;
						previousValue.Table_SANPHAMs.Remove(this);
					}
					this._Table_LOAISANPHAM.Entity = value;
					if ((value != null))
					{
						value.Table_SANPHAMs.Add(this);
						this._ID_LOAISANPHAM = value.ID_LOAISANPHAM;
					}
					else
					{
						this._ID_LOAISANPHAM = default(int);
					}
					this.SendPropertyChanged("Table_LOAISANPHAM");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_NhaSX_Table_SANPHAM", Storage="_Table_NhaSX", ThisKey="ID_NSX", OtherKey="ID_NSX", IsForeignKey=true)]
		public Table_NhaSX Table_NhaSX
		{
			get
			{
				return this._Table_NhaSX.Entity;
			}
			set
			{
				Table_NhaSX previousValue = this._Table_NhaSX.Entity;
				if (((previousValue != value) 
							|| (this._Table_NhaSX.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Table_NhaSX.Entity = null;
						previousValue.Table_SANPHAMs.Remove(this);
					}
					this._Table_NhaSX.Entity = value;
					if ((value != null))
					{
						value.Table_SANPHAMs.Add(this);
						this._ID_NSX = value.ID_NSX;
					}
					else
					{
						this._ID_NSX = default(Nullable<int>);
					}
					this.SendPropertyChanged("Table_NhaSX");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Table_TUYCHONs(Table_TUYCHON entity)
		{
			this.SendPropertyChanging();
			entity.Table_SANPHAM = this;
		}
		
		private void detach_Table_TUYCHONs(Table_TUYCHON entity)
		{
			this.SendPropertyChanging();
			entity.Table_SANPHAM = null;
		}
		
		private void attach_Table_DONHANG_DMs(Table_DONHANG_DM entity)
		{
			this.SendPropertyChanging();
			entity.Table_SANPHAM = this;
		}
		
		private void detach_Table_DONHANG_DMs(Table_DONHANG_DM entity)
		{
			this.SendPropertyChanging();
			entity.Table_SANPHAM = null;
		}
		
		private void attach_Table_MUCHINHANHs(Table_MUCHINHANH entity)
		{
			this.SendPropertyChanging();
			entity.Table_SANPHAM = this;
		}
		
		private void detach_Table_MUCHINHANHs(Table_MUCHINHANH entity)
		{
			this.SendPropertyChanging();
			entity.Table_SANPHAM = null;
		}
		
		private void attach_Table_NHAPKHOs(Table_NHAPKHO entity)
		{
			this.SendPropertyChanging();
			entity.Table_SANPHAM = this;
		}
		
		private void detach_Table_NHAPKHOs(Table_NHAPKHO entity)
		{
			this.SendPropertyChanging();
			entity.Table_SANPHAM = null;
		}
	}
}
#pragma warning restore 1591
